sonar.projectKey=VillegasMich_CICD
sonar.organization=villegasmich
sonar.sources=backend/app
sonar.python.version=3.12
sonar.python.pylint.reportPaths=backend/pylint-report.txt
sonar.python.flake8.reportPaths=backend/flake8-report.txt
sonar.coverage.exclusions=**/tests/**,**/setup.py,backend/app/__init__.py
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300